/*
 * @Author: Yang Liu
 * @Date: 2022-03-24 23:18:13
 * @LastEditors: Shen Shu
 * @LastEditTime: 2022-04-29 15:39:33
 * @FilePath: \bhpmJS\frontend\src\pages\business_info\Privacy.js
 * @Description:
 *
 * Copyright (c) 2022 by 用户/公司名, All Rights Reserved.
 */

import { Box, Container, styled } from "@mui/material";

import Navbar from "../../components/navbar/Navbar";
import React from "react";
import { useSelector } from "react-redux";

export default function AboutUs() {
  const { currentLanguage } = useSelector((state) => state.general.language);
  const InnerContainer = styled(Container)(() => ({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: "100%",
  }));

  return (
    <>
      <Navbar />

      <InnerContainer
        sx={{
          justifyContent: "left",
        }}
      >
        <Box>
          <h1>{currentLanguage === "zh_hk" ? "隱私政策" : "Privacy Policy"}</h1>
          {currentLanguage !== "zh_hk" ? (
            <>
              <p>
                In order to respect and protect your personal Privacy, the
                website has developed a Privacy Policy. This Policy sets out the
                company's policies and principles for collecting, using and
                protecting your personal data when you use the website. Please
                read it carefully.
                <br />
                <br />
                Scope of application
                <br />
                <br />
                The following privacy policy applies to the collection, use and
                protection of your personal data in connection with your
                activities on this website (www.bhpm.ca). However, this does not
                apply to your activities after you link to other websites
                through this website. For the protection of personal data of
                other websites, please refer to the privacy protection policy of
                corresponding websites.
                <br />
                <br />
                Data collection
                <br />
                <br />
                Depending on the services provided by this website, the
                following personal data may be collected from users:
                <br />
                <br />
                - The website does not collect any personally identifiable
                information solely for browsing on this website.
                <br />
                <br />
                - If you need to provide personal information through the online
                application services provided by this website, you will be asked
                to provide the latest and most true personal information such as
                item, ID number, contact telephone number, email address, etc.
                <br />
                <br />
                - If you express your views or ask relevant business questions
                through our service mailbox, we will keep your communication
                records for the purpose of contacting you only.
                <br />
                <br />
                - Logs generated by the server, including the IP address of the
                connected device, the time of use, all browsers, browsing and
                clicking records, etc., are used to summarize the browsing time
                of the user's browser and other pages within the website, so as
                to improve the service quality of the website.
                <br />
                <br />
                Sharing, disclosure and use of data
                <br />
                <br />
                The website will not sell, exchange, or rent any of your
                personal information to other parties or individuals. Only when
                the judicial authorities require the website to disclose certain
                personal information for the sake of public safety, the website
                will comply with the legal and formal procedures of the judicial
                authorities and make necessary cooperation for the safety of all
                users of the website.
                <br />
                <br />
                Policy on the use of Cookies
                <br />
                <br />
                In order to provide personalized services, the website will use
                Cookies to store and track users' data at certain times. You can
                choose to modify the browser's acceptance of Cookies in
                "Advanced" of "Function Settings" of Netscape or "Security" of
                "Internet Options" of IE, including accepting all Cookies,
                notifying the user when receiving Cookies, rejecting all
                Cookies, etc. If you choose to refuse all Cookies, you may not
                be able to use some of the personalized services or participate
                in some of the activities.
                <br />
                <br />
                Information security and protection
                <br />
                <br />
                The servers on this website are protected by firewalls to
                prevent unauthorized access, destruction or theft of data. Any
                data stored on this website will be fully protected to protect
                your personal data when you use the services of this website.
                <br />
                <br />
                Privacy protection policy revised
                <br />
                <br />
                The website will revise this policy from time to time to comply
                with the latest privacy protection standards.
                <br />
                <br />
                Privacy protection policy policy advisory
                <br />
                <br />
                If you have any comments or questions about our privacy policy,
                please write directly to us.
              </p>
              <br />
              <br />
            </>
          ) : (
            <>
              隱私權保護政策
              <br />
              <br />
              為了尊重及保護您的個人隱私，本網站制定了隱私權保護政策（Privacy
              Policy）。本政策規定了您使用本網站時，公司收集、運用及保護您的個人資料的政策與原則，請詳細閱讀。
              <br />
              <br />
              適用範圍
              <br />
              <br />
              以下的隱私權保護政策，適用於您在本網站（www.bhpm.ca）活動時所涉及的個人資料收集、運用與保護。但不適用於您通過本網站鏈接到其他網站後所進行的活動，關於其他網站的個人資料保護，請參閱相應網站的隱私權保護政策。
              <br />
              <br />
              資料收集
              <br />
              <br />
              根據本網站所提供的不同服務，可能向使用者收集以下個人資料：
              <br />
              -單純在本網站的瀏覽行為，本網站並不會收集任何有關個人的身份資料。
              <br />
              <br />
              -利用本網站所提供的各項線上申請服務，需申請人提供個人資料時，會根據需求請您提供項目、身份證件號碼、聯繫電話、email、通訊地址等個人最新、最真實的資料。
              <br />
              -如果您通過服務信箱反映您的意見或詢問相關業務問題，我們會保存您的通訊記錄，僅作為與您聯絡之用。
              <br />
              -服務器自行產生的相關記錄（LOG），包括連線設備IP地址、使用時間、所有的瀏覽器、瀏覽及點選資料記錄等，以歸納使用者瀏覽器在本網站內部所瀏覽等網頁以及瀏覽時間，以提升本網站的服務品質。
              <br />
              <br />
              資料的分享、公開及運用方式
              <br />
              <br />
              本網站不會任意出售、交換、或出租任何您的個人資料給其他團體或個人。只有在司法單位因公眾安全，要求本網站公開特定公開特定個人資料時，本網站將視司法單位合法正式的程序，以及對本網站所有使用者安全考量下做可能必要之配合。
              <br />
              <br />
              Cookies的運用政策
              <br />
              <br />
              為提供個人化的服務，本網站會使用Cookies技術來儲存並在某些時候追蹤網友的資料。在Netscape的「功能設定」的「進階」或是IE的「Internet選項」的「安全性」中可以選擇修改瀏覽器對Cookies的接受程度，包括接受所有Cookies、設定收到Cookies時通知使用者、拒絕所有Cookies等。如果您選擇拒絕所有的Cookies,可能無法使用部分個人化服務或是參與部分的活動。
              <br />
              <br />
              資訊安全及保護
              <br />
              <br />
              本網站的伺服器設有「防火牆」作保護，防止非法入侵、破壞或竊取資料，當您使用本網站之各項服務功能時，任何儲存存於本網站上之資料，會受到完善保護，以保障您的個人資料安全。
              <br />
              <br />
              隱私權保護政策修訂
              <br />
              <br />
              本網站會不定時修訂本項政策，以符合最新之隱私權保護規範。
              <br />
              <br />
              隱私權保護政策政策咨詢
              <br />
              <br />
              如果您對於本網站的隱私權保護政策有意見或問題，請直接來信洽詢。
              <br />
              <br />
            </>
          )}
        </Box>
      </InnerContainer>
    </>
  );
}
