/*
 * @Author: Yang Liu
 * @Date: 2022-03-24 23:18:13
 * @LastEditors: Shen Shu
 * @LastEditTime: 2022-04-29 13:49:53
 * @FilePath: \bhpmJS\frontend\src\pages\business_info\Privacy.js
 * @Description:
 *
 * Copyright (c) 2022 by 用户/公司名, All Rights Reserved.
 */

import { Box, Container, styled } from "@mui/material";

import Navbar from "../../components/navbar/Navbar";
import React from "react";
import { useSelector } from "react-redux";

export default function AboutUs() {
  const { currentLanguage } = useSelector((state) => state.general.language);
  const InnerContainer = styled(Container)(() => ({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: "100%",
  }));

  return (
    <>
      <Navbar />

      <InnerContainer
        sx={{
          justifyContent: "left",
        }}
      >
        <Box>
          <h1>{currentLanguage === "zh_hk" ? "隱私政策" : "Privacy Policy"}</h1>
          <p>
            In order to respect and protect your personal Privacy, the website
            has developed a Privacy Policy. This Policy sets out the company's
            policies and principles for collecting, using and protecting your
            personal data when you use the website. Please read it carefully.
            <br />
            <br />
            Scope of application
            <br />
            <br />
            The following privacy policy applies to the collection, use and
            protection of your personal data in connection with your activities
            on this website (www.bhpm.ca). However, this does not apply to your
            activities after you link to other websites through this website.
            For the protection of personal data of other websites, please refer
            to the privacy protection policy of corresponding websites.
            <br />
            <br />
            Data collection
            <br />
            <br />
            Depending on the services provided by this website, the following
            personal data may be collected from users:
            <br />
            <br />
            - The website does not collect any personally identifiable
            information solely for browsing on this website.
            <br />
            <br />
            - If you need to provide personal information through the online
            application services provided by this website, you will be asked to
            provide the latest and most true personal information such as item,
            ID number, contact telephone number, email address, etc.
            <br />
            <br />
            - If you express your views or ask relevant business questions
            through our service mailbox, we will keep your communication records
            for the purpose of contacting you only.
            <br />
            <br />
            - Logs generated by the server, including the IP address of the
            connected device, the time of use, all browsers, browsing and
            clicking records, etc., are used to summarize the browsing time of
            the user's browser and other pages within the website, so as to
            improve the service quality of the website.
            <br />
            <br />
            Sharing, disclosure and use of data
            <br />
            <br />
            The website will not sell, exchange, or rent any of your personal
            information to other parties or individuals. Only when the judicial
            authorities require the website to disclose certain personal
            information for the sake of public safety, the website will comply
            with the legal and formal procedures of the judicial authorities and
            make necessary cooperation for the safety of all users of the
            website.
            <br />
            <br />
            Policy on the use of Cookies
            <br />
            <br />
            In order to provide personalized services, the website will use
            Cookies to store and track users' data at certain times. You can
            choose to modify the browser's acceptance of Cookies in "Advanced"
            of "Function Settings" of Netscape or "Security" of "Internet
            Options" of IE, including accepting all Cookies, notifying the user
            when receiving Cookies, rejecting all Cookies, etc. If you choose to
            refuse all Cookies, you may not be able to use some of the
            personalized services or participate in some of the activities.
            <br />
            <br />
            Information security and protection
            <br />
            <br />
            The servers on this website are protected by firewalls to prevent
            unauthorized access, destruction or theft of data. Any data stored
            on this website will be fully protected to protect your personal
            data when you use the services of this website.
            <br />
            <br />
            Privacy protection policy revised
            <br />
            <br />
            The website will revise this policy from time to time to comply with
            the latest privacy protection standards.
            <br />
            <br />
            Privacy protection policy policy advisory
            <br />
            <br />
            If you have any comments or questions about our privacy policy,
            please write directly to us.
          </p>
          <br />
          <br />
        </Box>
      </InnerContainer>
    </>
  );
}
