/*
 * @Author: Yang Liu
 * @Date: 2022-03-24 23:18:13
 * @LastEditors: Shen Shu
 * @LastEditTime: 2022-04-29 15:21:53
 * @FilePath: \bhpmJS\frontend\src\pages\business_info\Privacy.js
 * @Description:
 *
 * Copyright (c) 2022 by 用户/公司名, All Rights Reserved.
 */

import { Box, Container, styled } from "@mui/material";

import Navbar from "../../components/navbar/Navbar";
import React from "react";
import { useSelector } from "react-redux";

export default function AboutUs() {
  const { currentLanguage } = useSelector((state) => state.general.language);
  const InnerContainer = styled(Container)(() => ({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: "100%",
  }));

  return (
    <>
      <Navbar />

      <InnerContainer
        sx={{
          justifyContent: "left",
        }}
      >
        <Box>
          <h1>{currentLanguage === "zh_hk" ? "隱私政策" : "Privacy Policy"}</h1>
          {currentLanguage !== "zh_hk" ? (
            <>
              <p>
                In order to respect and protect your personal Privacy, the
                website has developed a Privacy Policy. This Policy sets out the
                company's policies and principles for collecting, using and
                protecting your personal data when you use the website. Please
                read it carefully.
                <br />
                <br />
                Scope of application
                <br />
                <br />
                The following privacy policy applies to the collection, use and
                protection of your personal data in connection with your
                activities on this website (www.bhpm.ca). However, this does not
                apply to your activities after you link to other websites
                through this website. For the protection of personal data of
                other websites, please refer to the privacy protection policy of
                corresponding websites.
                <br />
                <br />
                Data collection
                <br />
                <br />
                Depending on the services provided by this website, the
                following personal data may be collected from users:
                <br />
                <br />
                - The website does not collect any personally identifiable
                information solely for browsing on this website.
                <br />
                <br />
                - If you need to provide personal information through the online
                application services provided by this website, you will be asked
                to provide the latest and most true personal information such as
                item, ID number, contact telephone number, email address, etc.
                <br />
                <br />
                - If you express your views or ask relevant business questions
                through our service mailbox, we will keep your communication
                records for the purpose of contacting you only.
                <br />
                <br />
                - Logs generated by the server, including the IP address of the
                connected device, the time of use, all browsers, browsing and
                clicking records, etc., are used to summarize the browsing time
                of the user's browser and other pages within the website, so as
                to improve the service quality of the website.
                <br />
                <br />
                Sharing, disclosure and use of data
                <br />
                <br />
                The website will not sell, exchange, or rent any of your
                personal information to other parties or individuals. Only when
                the judicial authorities require the website to disclose certain
                personal information for the sake of public safety, the website
                will comply with the legal and formal procedures of the judicial
                authorities and make necessary cooperation for the safety of all
                users of the website.
                <br />
                <br />
                Policy on the use of Cookies
                <br />
                <br />
                In order to provide personalized services, the website will use
                Cookies to store and track users' data at certain times. You can
                choose to modify the browser's acceptance of Cookies in
                "Advanced" of "Function Settings" of Netscape or "Security" of
                "Internet Options" of IE, including accepting all Cookies,
                notifying the user when receiving Cookies, rejecting all
                Cookies, etc. If you choose to refuse all Cookies, you may not
                be able to use some of the personalized services or participate
                in some of the activities.
                <br />
                <br />
                Information security and protection
                <br />
                <br />
                The servers on this website are protected by firewalls to
                prevent unauthorized access, destruction or theft of data. Any
                data stored on this website will be fully protected to protect
                your personal data when you use the services of this website.
                <br />
                <br />
                Privacy protection policy revised
                <br />
                <br />
                The website will revise this policy from time to time to comply
                with the latest privacy protection standards.
                <br />
                <br />
                Privacy protection policy policy advisory
                <br />
                <br />
                If you have any comments or questions about our privacy policy,
                please write directly to us.
              </p>
              <br />
              <br />
            </>
          ) : (
            <>
              —隐私条款
              <br />
              <br />
              隐私权保护政策
              <br />
              <br />
              为了尊重及保护您的个人隐私，本网站制定了隐私权保护政策（Privacy
              Policy）。本政策规定了您使用本网站时，公司收集、运用及保护您的个人资料的政策与原则，请详细阅读。
              <br />
              <br />
              适用范围
              <br />
              <br />
              以下的隐私权保护政策，适用于您在本网站（www.bhpm.ca）活动时所涉及的个人资料收集、运用与保护。但不适用于您通过本网站链接到其他网站后所进行的活动，关于其他网站的个人资料保护，请参阅相应网站的隐私权保护政策。
              <br />
              <br />
              资料收集
              <br />
              <br />
              根据本网站所提供的不同服务，可能向使用者收集以下个人资料： <br />
              <br />
              -单纯在本网站的浏览行为，本网站并不会收集任何有关个人的身份资料。
              <br />
              -利用本网站所提供的各项线上申请服务，需申请人提供个人资料时，会根据需求请您提供项目、身份证件号码、联系电话、email、通讯地址等个人最新、最真实的资料。
              <br />
              -如果您通过服务信箱反映您的意见或询问相关业务问题，我们会保存您的通讯记录，仅作为与您联络之用。
              <br />
              -服务器自行产生的相关记录（LOG），包括连线设备IP地址、使用时间、所有的浏览器、浏览及点选资料记录等，以归纳使用者浏览器在本网站内部所浏览等网页以及浏览时间，以提升本网站的服务品质。
              <br />
              <br />
              资料的分享、公开及运用方式
              <br />
              <br />
              本网站不会任意出售、交换、或出租任何您的个人资料给其他团体或个人。只有在司法单位因公众安全，要求本网站公开特定公开特定个人资料时，本网站将视司法单位合法正式的程序，以及对本网站所有使用者安全考量下做可能必要之配合。
              <br />
              <br />
              Cookies的运用政策
              <br />
              <br />
              为提供个人化的服务，本网站会使用Cookies技术来储存并在某些时候追踪网友的资料。在Netscape的“功能设定”的“进阶”或是IE的“Internet选项”的“安全性”中可以选择修改浏览器对Cookies的接受程度，包括接受所有Cookies、设定收到Cookies时通知使用者、拒绝所有Cookies等。如果您选择拒绝所有的Cookies,可能无法使用部分个人化服务或是参与部分的活动。
              <br />
              <br />
              资讯安全及保护
              <br />
              <br />
              本网站的伺服器设有“防火墙”作保护，防止非法入侵、破坏或窃取资料，当您使用本网站之各项服务功能时，任何储存存于本网站上之资料，会受到完善保护，以保障您的个人资料安全。
              <br />
              <br />
              隐私权保护政策修订
              <br />
              <br />
              本网站会不定时修订本项政策，以符合最新之隐私权保护规范。
              <br />
              <br />
              隐私权保护政策政策咨询
              <br />
              <br />
              如果您对于本网站的隐私权保护政策有意见或问题，请直接来信洽询。
            </>
          )}
        </Box>
      </InnerContainer>
    </>
  );
}
